missing_formula: TexLive is only blacklisted on macOS
- In Homebrew/linuxbrew-core, [we have a Linux-only formula for
  `texlive`](https://github.com/Homebrew/linuxbrew-core/tree/master/Formula/texlive.rb).
- When running `brew audit --strict texlive` on Linux, we got the
  following messaging:

  ```
  $ brew audit --strict texlive
  texlive:
    * 'texlive' is blacklisted from homebrew/core.
    Error: 1 problem in 1 formula detected
  ```

- Looking at where this comes from leads to the missing formula
  messaging to install `mactex` via Homebrew Cask. The 'blacklisted in
  homebrew/core' messaging only applies to macOS where Casks are an option
  for users, so let's not surface the audit for `texlive` on Linux.