Revert "Enable patchelf.rb for HOMEBREW_DEVELOPERs."
This reverts commit 6106bfc4976dff2b03cf3fadbbf92dd1fd9e0f09.

Fix the error:
brew install patchelf
==> Pouring patchelf-0.10.x86_64_linux.bottle.1.tar.gz
Error: cannot load such file -- patchelf