bump-formula-pr: fix forking error when formula is guessed from url
Regression introduced in f90612ccf0db03681dc6cbf6585cca5bc27b84b1 (#6718).

`tap_full_name` returned from `use_correct_linux_tap` has been
required (`GitHub.create_fork(tap_full_name)`), but it was never set when the
formula is guessed from args.url, resulting in an API request to
https://api.github.com/repos//forks which 404s (note the missing :owner/:repo),
and subsequently

    Error: Unable to fork: Not Found!