formula_cellar_checks: skip unless Python libs
This avoids an unusual error message when Python is needed for building
(e.g., code generation) but is not used at runtime.

```
==> brew audit recode --online
Error: 1 problem in 1 formula detected
recode:
  * Packages have been installed for:

    but this formula depends on:
      Python 3.7
```