cmd/install: output missing formula name.
Otherwise if there's no search results then there's no indication what
was being searched for:

```
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```