bintray: Fix "uninitialized constant EnvConfig" errors
- This fix was suggested by Sorbet when I ran `HOMEBREW_SORBET=1 bundle
  exec srb tc` on the latest `master` while playing around with the
  latest changes post-GSoC meeting.
- Then I noticed it was actually a bug, introduced in
  adc36a05ffeadb54b94c87d86f62fba9dbb86795, found by us not being able to
  publish bottles for [this build of the `n`
  formula](https://github.com/Homebrew/homebrew-core/runs/910309641?check_suite_focus=true)
  in https://github.com/Homebrew/homebrew-core/pull/58606:

```
[master 31d32307bd] n: update 6.7.0 bottle.
 1 file changed, 3 insertions(+), 3 deletions(-)
curl: (22) The requested URL returned error: 404 Not Found
Error: uninitialized constant Bintray::EnvConfig
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:28:in `open_api'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:43:in `upload'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:186:in `block (2 levels) in upload_bottle_json'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:158:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:158:in `block in upload_bottle_json'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:153:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/bintray.rb:153:in `upload_bottle_json'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-upload.rb:54:in `pr_upload'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew pr-upload --verbose --bintray-org=homebrew` exited with 1.
```